import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryProvider from "../../utils/QueryProvider";
import Slider from "./components/Slider";
import SliderEmp from "./components/SliderEmp";
import Header from "./components/Header";
import { NextAuthProvider } from "./providers";
import { getServerSession } from "next-auth";
import { authOptions } from "../../utils/authOptions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  console.log("session layout", session?.userData.role);
  return (
    <NextAuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <QueryProvider>
            {session ? (
              <>
                <Header />
                {session?.userData.role === "admin" ? (
                  <Slider>{children}</Slider>
                ) : (
                  <SliderEmp>{children}</SliderEmp>
                )}
              </>
            ) : (
              children
            )}
          </QueryProvider>
        </body>
      </html>
    </NextAuthProvider>
  );
}
